### ISSUE TITLE
Create ScheduledCheck

### ISSUE THREAD

**Issue by maxnoe** [fact-project/pycustos#7]
I think a check that runs at certain scheduled times would be helpful.

We might want to use the `apscheduler` package.

**Comment by kbruegge** [comment]
How about [https://github.com/dbader/schedule](https://github.com/dbader/schedule) ?
I really like its API.

**Comment by dneise** [comment]
comparing dbaders schedule with apschedule documentationwise, apscheduler has more docu, but appently also needs it, while dbaders API seems to be really clean. Impressive how easy one can make scheduling look.

**Comment by maxnoe** [comment]
The API is really nice, but it seems that it cannot be used via keyword arguments which is the case with apscheduler. Let's continue discussion in the PR #8 . We can discuss actual code there.
